services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
    # depends_on:
    #   - db
  
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    image: nginx-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - .env.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data/
    environment:
      REDIS_PASSWORD: lpthinh
      REDIS_PORT: 6379
      REDIS_DATABASES: 1

volumes:
  static_volume:
  media_volume:
  redis_data:
  certs:
  html:
  vhost:
  acme: