# Generated by Django 5.1.5 on 2025-01-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_optional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('registration_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_student', models.BooleanField(default=True)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.combination')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('subject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.subject')),
                ('type', models.CharField(choices=[('N1', 'ENGLISH'), ('N2', 'Russian'), ('N3', 'French'), ('N4', 'Chinese'), ('N5', 'German'), ('N6', 'Japanese'), ('N7', 'Korean')], default='N1', max_length=10)),
            ],
            bases=('app.subject',),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.combination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
