# Generated by Django 5.1.5 on 2025-01-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcombination',
            name='combination',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='combination',
        ),
        migrations.RemoveField(
            model_name='subjectcombination',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Combination',
        ),
        migrations.DeleteModel(
            name='SubjectCombination',
        ),
    ]
