# Generated by Django 5.1.5 on 2025-01-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subjectcombination_combination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='subject_ptr',
        ),
        migrations.AddField(
            model_name='candidate',
            name='language',
            field=models.CharField(choices=[('N1', 'ENGLISH'), ('N2', 'Russian'), ('N3', 'French'), ('N4', 'Chinese'), ('N5', 'German'), ('N6', 'Japanese'), ('N7', 'Korean')], default='N1', max_length=10),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ForeignLanguage',
        ),
    ]
