# Generated by Django 5.1.5 on 2025-01-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_candidate_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_optional',
        ),
        migrations.CreateModel(
            name='ForeignScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foreignlanguage')),
            ],
        ),
    ]
