# Generated by Django 5.1.5 on 2025-01-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foreignlanguage_remove_candidate_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignscore',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='app.candidate'),
        ),
        migrations.AlterField(
            model_name='foreignscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='app.foreignlanguage'),
        ),
        migrations.AlterField(
            model_name='score',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.candidate'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.subject'),
        ),
    ]
